### ISSUE TITLE
services are not created when launching create-stack command

### ISSUE THREAD

**Issue by nelutzu25** [RetailMeNotSandbox/ecs-selenium#23]

**Comment by robertoriv** [comment]
@nelutzu25, are you getting any error in the cloudformation console?

Let us know and we'll try to help you debug it.

**Comment by nelutzu25** [comment]
@robertoriv , thanks for replying! There is no error in the cloudformation console. The only info I have here is that ChromeHubService, FirefoxHubService, NodeFirefoxService always show the status "CREATE_IN_PROGRESS" inside the console. And therefore the creation is never finished.

**Comment by robertoriv** [comment]
That usually means that the service didn't stabilize. (The containers didn't come up, or they crashed on startup.)

There are a couple of reasons why this can happen:
* You don't have any/enough EC2 instances to put containers on. This could happen if your bid price was too low, for example. (This is unlikely to be your problem, because the hub instances are on-demand, and those services didn't come up either.)
* Some error is making the containers crash.

I cover the first one -- as it relates to SpotFleet -- in the README: https://github.com/RetailMeNotSandbox/ecs-selenium#errors-that-occur-when-creating-the-stack

You can take a look at the services in the ECS console. There may be some errors in there that can shed some light. You can also verify if there are any instances available for placing the containers. 

You should also look at the logstream in CloudWatch (`ecs-selenium`) and check if the containers errored out.

**Comment by nelutzu25** [comment]
I found something: the tasks which are running on the ecs-selenium-nodes cluster all crash with this error -> 
standard_init_linux.go:190: exec user process caused "no such file or directory"

I have 3 EC2 instances available, 2 for the nodes, 1 for the hub:
![image](https://user-images.githubusercontent.com/4963692/65666187-6db95480-e03d-11e9-905f-9bea6970c468.png) .
Not sure if this is the problem.

By the way, is there a way to make the entire infrastructure rely on regular EC2 instances, without having to bid for them?

**Comment by nelutzu25** [comment]
I managed to solve that problem with the answer from here: https://stackoverflow.com/a/52665687/3211850 . I had to rebuild the docker files. Now the stack is created, but I have another issue that was already reported here: https://github.com/RetailMeNotSandbox/ecs-selenium/issues/20 . But I am not sure how can I vpn into the vpc. Can I make the Selenium Hub URL publicly available, instead?

EDIT: Solved the problem by referencing an existing public HostedZone, from the Firefox/Chrome Record.
