### ISSUE TITLE
Unable to Create Stack

### ISSUE THREAD

**Issue by elijahchancey** [RetailMeNotSandbox/ecs-selenium#6]
When I try to create the Cloudformation stack, I see this error:
```
Service arn:aws:ecs:us-west-1:988474017641:service/ecs-node-firefox did not stabilize.
```
https://www.dropbox.com/s/b9gwvutpvetio0p/Screenshot%202018-02-23%2014.05.26.png?dl=0

Here are the logs I was able to gather through Cloudwatch:
https://www.dropbox.com/s/c65qkxqqiyg5yyq/Screenshot%202018-02-23%2014.07.59.png?dl=0
https://www.dropbox.com/s/yi0vvapn5l6qm08/Screenshot%202018-02-23%2014.08.18.png?dl=0
https://www.dropbox.com/s/gt320keetyv6mzt/Screenshot%202018-02-23%2014.08.34.png?dl=0

What can I do to gather further debugging information? Thanks!

**Comment by robertoriv** [comment]
> Service arn:aws:ecs:us-west-1:988474017641:service/ecs-node-firefox did not stabilize.

We've seen this in situations where the cluster is unable to provision the desired amount of nodes. There will be a mismatch between the *Desired tasks* value and the *Running tasks* value in the ECS console (`Elastic Container Service -> ecs-selenium-nodes -> Services (tab)`.

It's usually due to hardware capacity. Here's what I would check:

1. Did you actually get any spot instances? (`EC2 -> Spot Requests -> Capacity Column (in the table)` 

    If you didn't get any instances, your bid price may be too low for the region. You can update the `MaxSpotBidPrice` parameter to something that works for you. (The default is set pretty low, so depending on the region, you may be outbid by others.)

    You can look at the SpotFleet's _History_ tab, and it will tell you if it was unable to provision instances due to your bid being too low.

2. Do you have enough EC2 capacity for the number of nodes you _desire_?
    
    [MemoryReservation](https://github.com/RetailMeNotSandbox/ecs-selenium/blob/master/cloudformation/ecs-selenium.cfn.yml#L739) is set to `1024` per node. So you'd need `1024 MB * Number of Desired Nodes` for it to provision successfully.

    If you don't have enough instances for your nodes, you can increase `DesiredFleetCapacity` to match it, or you can decrease `DesiredChromeNodes` and `DesiredFirefoxNodes` to a number that fits within your provisioned instances.

The fact that you don't have any entries in the `ecs-selenium-nodes` stream seems to indicate that it never provisioned a single node. So I'd start by looking at the SpotFleet.

**Comment by elijahchancey** [comment]
Thanks for the update! Increasing the MaxSpotBidPrice fixed the issue.

Sent via carrier pigeon,
Elijah Chancey
(415) 508 3777
elijahchancey.com <http://www.elijahchancey.com>
Schedule a Call via Calendly
<https://calendly.com/elijahchancey/infrastructure_consultation>
